### ISSUE TITLE
esm import results in faulty cjs require

### ISSUE THREAD

**Issue by woldtwerk** [unjs/unimport#230] opened 2023-03-20 08:38 UTC
### Environment

18.15.0

### Reproduction

```ts
import Unimport from 'unimport/unplugin'

export default (options: UserOptions = {}): Plugin[] => {
return [
   ...
    UnimportPlugin.vite(),
    ...
  ].flat()
}

```

### Describe the bug

gets compiled to:

```cjs
const index = (options = {}) => {
const Unimport = require('unimport/unplugin');
const UnimportPlugin = "default" in Unimport ? Unimport.default : Unimport;
  return [
    ...
    Unimport.vite(),
    ...
  ].flat();
};

module.exports = index;
```

It should be `Unimport.default.vite` though

is this an issue with unimport or unbuild?

I'm using `"unbuild": "^1.1.2"`

### Additional context

The use case is that I have a meta plugin that preconfigures a bunch of plugins.

I have a workaround, but would like to know why this happens.
Thank you =)

**Comment by antfu** [comment] 2023-03-20 08:48
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-03-20 08:48 UTC

**Comment by woldtwerk** [comment] 2023-03-20 12:51
sry, I will try to add a minimal reproduction asap

**Comment by woldtwerk** [comment] 2023-03-20 18:55
Hi Anthony,
here is the minimal reproduction:
https://stackblitz.com/edit/vitejs-vite-pn4bba?file=plugin/dist/index.cjs
